// CLIProxyAPI sidecar manager.
//
// Lifecycle: spawn `cli-proxy-api.exe` with `-config <minimal-yaml>`, wait
// for HTTP readiness, expose `{ baseUrl, apiKey, isRunning, stop }`. The
// API key is generated fresh on every start (cryptographic random hex);
// it lives in memory + the on-disk config and never reaches git.
//
// Update flow (zero code changes for upstream version bumps):
//   - `pnpm cliproxy:update` rewrites VERSION.json (incl. `binary` if the
//     upstream filename shifted)
//   - `resolveCliproxyBinary()` reads VERSION.json, doesn't hardcode names
//   - The only spawn arg we pass is `-config <path>`. If a future version
//     renames that flag, this file changes by ~1 line — minimal.
//
// Auth: the user runs `cli-proxy-api.exe -claude-login` (or codex / gemini
// login flags) ONCE to authorize the proxy against their accounts. The
// resulting tokens live in `<auth-dir>` and are reused across launches.

import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { spawn, type ChildProcess } from "node:child_process";
import { setTimeout as delay } from "node:timers/promises";
import {
	cliproxyAuthDir,
	cliproxyConfigDir,
	resolveCliproxyBinary,
	type ResolvedBinary,
} from "./paths.js";

const READY_TIMEOUT_MS_DEFAULT = 30_000;
const READY_POLL_MS = 250;
const STOP_GRACE_MS = 5_000;

export interface CliProxyManagerOptions {
	/** Override binary location (otherwise resolved from env/install/vendor). */
	binaryPath?: string;
	/** Override config dir (default: %LocalAppData%\OfficeAIAssistant\config\cliproxy). */
	configDir?: string;
	/** Override auth dir (default: %LocalAppData%\OfficeAIAssistant\auth\cliproxy). */
	authDir?: string;
	/** Bind host. Default 127.0.0.1 (loopback only). */
	host?: string;
	/** Bind port. Default 8317. */
	port?: number;
	/** Inject for tests. Defaults to `node:child_process.spawn`. */
	spawnFn?: typeof spawn;
	/** Inject for readiness probe. Defaults to global `fetch`. */
	fetchFn?: typeof fetch;
}

export interface CliProxyStartResult {
	baseUrl: string;
	apiKey: string;
	pid: number | undefined;
	binarySource: ResolvedBinary["source"] | "override";
}

export class CliProxyManager {
	private readonly host: string;
	private readonly port: number;
	private readonly configDir: string;
	private readonly authDir: string;
	private readonly resolvedBinary: { path: string; source: ResolvedBinary["source"] | "override" };
	private readonly spawnFn: typeof spawn;
	private readonly fetchFn: typeof fetch;

	private child: ChildProcess | null = null;
	private apiKey: string | null = null;
	private exitListeners: Array<(code: number | null) => void> = [];

	constructor(opts: CliProxyManagerOptions = {}) {
		this.host = opts.host ?? "127.0.0.1";
		this.port = opts.port ?? 8317;
		this.configDir = opts.configDir ?? cliproxyConfigDir();
		this.authDir = opts.authDir ?? cliproxyAuthDir();
		this.spawnFn = opts.spawnFn ?? spawn;
		this.fetchFn = opts.fetchFn ?? fetch;

		if (opts.binaryPath) {
			this.resolvedBinary = { path: opts.binaryPath, source: "override" };
		} else {
			const r = resolveCliproxyBinary();
			if (!r) {
				throw new Error(
					"CLIProxyAPI binary not found. Run `pnpm fetch:cliproxy` (dev) or install via the per-user installer.",
				);
			}
			this.resolvedBinary = r;
		}
	}

	/** http://host:port — the sidecar adapter prefixes this with /api/provider/<vendor>/v1. */
	getRootUrl(): string {
		return `http://${this.host}:${this.port}`;
	}

	getApiKey(): string | null {
		return this.apiKey;
	}

	isRunning(): boolean {
		return this.child !== null && this.child.exitCode === null;
	}

	private writeConfig(): string {
		mkdirSync(this.configDir, { recursive: true });
		mkdirSync(this.authDir, { recursive: true });
		const configPath = join(this.configDir, "config.yaml");
		// Minimal config — only what we need. Anything else uses upstream
		// defaults so future upstream versions don't break us.
		const yaml = [
			`# Auto-generated by office-ai-assistant bridge. Do not edit by hand —`,
			`# the bridge rewrites this file on every CliProxyManager.start().`,
			`host: "${this.host}"`,
			`port: ${this.port}`,
			`auth-dir: "${this.authDir.replace(/\\/g, "/")}"`,
			`api-keys:`,
			`  - "${this.apiKey}"`,
			`debug: false`,
			`logging-to-file: false`,
			`usage-statistics-enabled: false`,
			`remote-management:`,
			`  allow-remote: false`,
			`  secret-key: ""`,
			"",
		].join("\n");
		writeFileSync(configPath, yaml, "utf8");
		return configPath;
	}

	async start(opts: { readyTimeoutMs?: number } = {}): Promise<CliProxyStartResult> {
		if (this.isRunning()) {
			throw new Error("CliProxyManager.start: already running");
		}
		this.apiKey = randomBytes(24).toString("hex");
		const configPath = this.writeConfig();
		const child = this.spawnFn(this.resolvedBinary.path, ["-config", configPath], {
			stdio: ["ignore", "pipe", "pipe"],
			windowsHide: true,
		});
		this.child = child;
		child.on("exit", (code) => {
			for (const cb of this.exitListeners) cb(code);
			this.exitListeners = [];
		});
		// Drain stdout/stderr so the OS pipe buffer doesn't block the child.
		// Bridge log layer can subscribe via onLog if/when we add it.
		child.stdout?.on("data", () => {});
		child.stderr?.on("data", () => {});

		try {
			await this.waitReady(opts.readyTimeoutMs ?? READY_TIMEOUT_MS_DEFAULT);
		} catch (e) {
			await this.stop();
			throw e;
		}
		return {
			baseUrl: this.getRootUrl(),
			apiKey: this.apiKey,
			pid: child.pid,
			binarySource: this.resolvedBinary.source,
		};
	}

	async stop(): Promise<void> {
		if (!this.child) return;
		const child = this.child;
		this.child = null;
		if (child.exitCode !== null) return;
		const exited = new Promise<void>((resolve) => {
			this.exitListeners.push(() => resolve());
		});
		child.kill("SIGTERM");
		await Promise.race([exited, delay(STOP_GRACE_MS)]);
		if (child.exitCode === null) {
			child.kill("SIGKILL");
			await Promise.race([exited, delay(1_000)]);
		}
	}

	/**
	 * Poll a stable upstream-version-agnostic endpoint until it responds 200.
	 * We use `/v0/health` if it exists (upstream added it for the panel) and
	 * fall back to a 401 on `/v1/models` — even an unauthorized response from
	 * `/v1/models` is proof the HTTP server is up.
	 */
	private async waitReady(timeoutMs: number): Promise<void> {
		const deadline = Date.now() + timeoutMs;
		const url = `${this.getRootUrl()}/v1/models`;
		let lastErr: string = "";
		while (Date.now() < deadline) {
			if (!this.isRunning()) {
				throw new Error(
					`CLIProxyAPI exited before becoming ready (last error: ${lastErr || "unknown"})`,
				);
			}
			try {
				const res = await this.fetchFn(url, {
					method: "GET",
					headers: this.apiKey
						? { authorization: `Bearer ${this.apiKey}` }
						: {},
				});
				// Any HTTP response = the server bound the port. 401/403 are
				// acceptable readiness signals (means auth layer is up but the
				// caller hasn't logged in yet).
				if (res.status >= 200 && res.status < 500) return;
				lastErr = `${res.status} ${res.statusText}`;
			} catch (e) {
				lastErr = (e as Error).message;
			}
			await delay(READY_POLL_MS);
		}
		throw new Error(
			`CLIProxyAPI did not become ready within ${timeoutMs}ms (last error: ${lastErr})`,
		);
	}
}
