export const BRIDGE_PROTOCOL_VERSION = 1;
// Bind/connect host: "127.0.0.1" loopback IPv4 ONLY (per ARCHITECTURE §1a).
// Avoids "localhost" name-resolution drift (IPv6 ::1 vs IPv4) and ensures the
// cert's SAN matches without ambiguity.
export const DEFAULT_BRIDGE_HOST = "127.0.0.1";
export const DEFAULT_BRIDGE_PORT = 4017;
export const DEFAULT_BRIDGE_WS_PATH = "/ws";
export const DEFAULT_BRIDGE_HTTP_URL = `https://${DEFAULT_BRIDGE_HOST}:${DEFAULT_BRIDGE_PORT}`;
export const DEFAULT_BRIDGE_WS_URL = `wss://${DEFAULT_BRIDGE_HOST}:${DEFAULT_BRIDGE_PORT}${DEFAULT_BRIDGE_WS_PATH}`;
export const DEFAULT_REQUEST_TIMEOUT_MS = 30_000;
export const DEFAULT_EVENT_LIMIT = 200;

export type BridgeApp = "excel" | "powerpoint" | "word" | (string & {});

export interface BridgeToolDefinition {
  name: string;
  label?: string;
  description?: string;
  parameters?: unknown;
}

export interface BridgeHostInfo {
  host?: string;
  platform?: string;
  officeVersion?: string;
  userAgent?: string;
  href: string;
  title?: string;
}

export interface BridgeSessionSnapshot {
  sessionId: string;
  instanceId: string;
  app: BridgeApp;
  appName?: string;
  appVersion?: string;
  metadataTag?: string;
  documentId: string;
  documentMetadata?: unknown;
  tools: BridgeToolDefinition[];
  host: BridgeHostInfo;
  connectedAt: number;
  updatedAt: number;
}

export interface BridgeError {
  message: string;
  code?: string;
  stack?: string;
}

export interface BridgeHelloMessage {
  type: "hello";
  role: "office-addin";
  protocolVersion: number;
  snapshot: BridgeSessionSnapshot;
}

export interface BridgeWelcomeMessage {
  type: "welcome";
  protocolVersion: number;
  serverTime: number;
}

export type BridgeInvokeMethod =
  | "ping"
  | "get_session_snapshot"
  | "refresh_session"
  | "execute_tool"
  | "execute_unsafe_office_js"
  | "vfs_list"
  | "vfs_read"
  | "vfs_write"
  | "vfs_delete";

export interface BridgeInvokeMessage {
  type: "invoke";
  requestId: string;
  method: BridgeInvokeMethod;
  params?: unknown;
}

export interface BridgeResponseMessage {
  type: "response";
  requestId: string;
  ok: boolean;
  result?: unknown;
  error?: BridgeError;
}

export interface BridgeEventMessage {
  type: "event";
  event: string;
  ts: number;
  payload?: unknown;
}

// ---------- Chat dispatch (Module 3) ----------
//
// Direction: chat_request and chat_abort go taskpane → bridge.
// chat_chunk goes bridge → taskpane (one per ChatChunk yielded by the
// chosen provider's adapter). The terminal frame is always a chunk with
// `kind: "done"` — taskpanes use it to flip UI state out of "streaming".
//
// requestId is opaque, generated by the taskpane. Bridges don't enforce
// uniqueness across sessions, but they do reject concurrent reuse within
// a single session via the dispatcher's abort-table.

/** Chat message sent to the provider. Mirrors providers/types.ChatMessage. */
export interface BridgeChatMessage {
  role: "system" | "user" | "assistant" | "tool";
  content: string;
  tool_call_id?: string;
  tool_name?: string;
}

export interface BridgeChatRequestPayload {
  messages: BridgeChatMessage[];
  model?: string;
  temperature?: number;
  top_p?: number;
  max_tokens?: number;
}

export interface BridgeChatRequestMessage {
  type: "chat_request";
  requestId: string;
  /** Provider registry id (e.g. "cli:claude"). */
  providerId: string;
  request: BridgeChatRequestPayload;
}

/** ChatChunk — discriminated union mirroring providers/types.ChatChunk. */
export type BridgeChatChunk =
  | { kind: "text"; delta: string }
  | { kind: "tool_call"; id: string; name: string; argsJson: string }
  | { kind: "tool_result"; id: string; resultJson: string }
  | { kind: "error"; message: string; recoverable?: boolean }
  | {
      kind: "done";
      reason?: "stop" | "length" | "tool_call" | "error" | "abort";
    };

export interface BridgeChatChunkMessage {
  type: "chat_chunk";
  requestId: string;
  chunk: BridgeChatChunk;
}

export interface BridgeChatAbortMessage {
  type: "chat_abort";
  requestId: string;
}

export type BridgeWireMessage =
  | BridgeHelloMessage
  | BridgeWelcomeMessage
  | BridgeInvokeMessage
  | BridgeResponseMessage
  | BridgeEventMessage
  | BridgeChatRequestMessage
  | BridgeChatChunkMessage
  | BridgeChatAbortMessage;

export interface BridgeStoredEvent {
  id: string;
  event: string;
  ts: number;
  payload?: unknown;
}

export interface BridgeInvokeRequest {
  sessionId: string;
  method: BridgeInvokeMethod;
  params?: unknown;
  timeoutMs?: number;
}

export interface BridgeToolExecutionResult {
  toolCallId: string;
  toolName: string;
  isError: boolean;
  result: unknown;
  resultText: string;
  images: Array<{ data: string; mimeType: string }>;
  error?: string;
}

export interface BridgeUnsafeOfficeJsParams {
  code: string;
  explanation?: string;
}

export interface BridgeUnsafeOfficeJsResult {
  mode: "unsafe";
  app: string;
  result: unknown;
}

export interface BridgeVfsEntry {
  path: string;
  byteLength: number;
}

export interface BridgeVfsListParams {
  prefix?: string;
}

export interface BridgeVfsReadParams {
  path: string;
  encoding?: "text" | "base64";
}

export interface BridgeVfsReadResult {
  path: string;
  encoding: "text" | "base64";
  byteLength: number;
  text?: string;
  dataBase64?: string;
}

export interface BridgeVfsWriteParams {
  path: string;
  text?: string;
  dataBase64?: string;
}

export interface BridgeVfsDeleteParams {
  path: string;
}

export function uint8ArrayToBase64(data: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < data.length; i++) {
    binary += String.fromCharCode(data[i]);
  }
  return btoa(binary);
}

interface ToolTextPart {
  type: "text";
  text: string;
}

interface ToolImagePart {
  type: "image";
  data: string;
  mimeType: string;
}

interface ToolResultLike {
  content?: Array<ToolTextPart | ToolImagePart | Record<string, unknown>>;
  details?: unknown;
}

export function createBridgeId(prefix = "bridge"): string {
  if (
    typeof crypto !== "undefined" &&
    typeof crypto.randomUUID === "function"
  ) {
    return `${prefix}_${crypto.randomUUID()}`;
  }
  return `${prefix}_${Math.random().toString(36).slice(2)}_${Date.now().toString(36)}`;
}

export function normalizeBridgeUrl(
  value: string | undefined,
  kind: "ws" | "http",
): string {
  if (!value) {
    return kind === "ws" ? DEFAULT_BRIDGE_WS_URL : DEFAULT_BRIDGE_HTTP_URL;
  }

  const raw = value.trim();
  if (!raw) {
    return kind === "ws" ? DEFAULT_BRIDGE_WS_URL : DEFAULT_BRIDGE_HTTP_URL;
  }

  if (/^wss?:\/\//i.test(raw) || /^https?:\/\//i.test(raw)) {
    const url = new URL(raw);
    if (kind === "ws") {
      if (url.protocol === "http:") url.protocol = "ws:";
      if (url.protocol === "https:") url.protocol = "wss:";
      if (!url.pathname || url.pathname === "/") {
        url.pathname = DEFAULT_BRIDGE_WS_PATH;
      }
    } else {
      if (url.protocol === "ws:") url.protocol = "http:";
      if (url.protocol === "wss:") url.protocol = "https:";
      if (url.pathname === DEFAULT_BRIDGE_WS_PATH) {
        url.pathname = "/";
      }
    }
    return url.toString().replace(/\/$/, "");
  }

  const url = new URL(
    `${kind === "ws" ? "wss" : "https"}://${raw.replace(/^\/+/, "")}`,
  );
  if (kind === "ws" && (!url.pathname || url.pathname === "/")) {
    url.pathname = DEFAULT_BRIDGE_WS_PATH;
  }
  return url.toString().replace(/\/$/, "");
}

export function serializeForJson(value: unknown): unknown {
  try {
    return JSON.parse(
      JSON.stringify(value, (_key, current) => {
        if (current instanceof Error) {
          return {
            name: current.name,
            message: current.message,
            stack: current.stack,
          };
        }
        if (current instanceof Uint8Array) {
          return {
            type: "Uint8Array",
            byteLength: current.byteLength,
          };
        }
        if (typeof current === "bigint") {
          return current.toString();
        }
        return current;
      }),
    );
  } catch {
    try {
      return String(value);
    } catch {
      return "[unserializable]";
    }
  }
}

export function toBridgeError(error: unknown): BridgeError {
  if (error instanceof Error) {
    return {
      message: error.message,
      stack: error.stack,
    };
  }
  return {
    message: typeof error === "string" ? error : "Unknown bridge error",
  };
}

export function isBridgeHelloMessage(
  value: unknown,
): value is BridgeHelloMessage {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as BridgeHelloMessage).type === "hello"
  );
}

export function isBridgeResponseMessage(
  value: unknown,
): value is BridgeResponseMessage {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as BridgeResponseMessage).type === "response"
  );
}

export function isBridgeEventMessage(
  value: unknown,
): value is BridgeEventMessage {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as BridgeEventMessage).type === "event"
  );
}

export function isBridgeInvokeMessage(
  value: unknown,
): value is BridgeInvokeMessage {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as BridgeInvokeMessage).type === "invoke"
  );
}

export function isBridgeChatRequestMessage(
  value: unknown,
): value is BridgeChatRequestMessage {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as BridgeChatRequestMessage).type === "chat_request"
  );
}

export function isBridgeChatChunkMessage(
  value: unknown,
): value is BridgeChatChunkMessage {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as BridgeChatChunkMessage).type === "chat_chunk"
  );
}

export function isBridgeChatAbortMessage(
  value: unknown,
): value is BridgeChatAbortMessage {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as BridgeChatAbortMessage).type === "chat_abort"
  );
}

/**
 * Map the provider-internal ChatChunk shape (`type` discriminant) onto the
 * wire ChatChunk shape (`kind` discriminant) so the taskpane never depends
 * on the bridge's internal type names. Internal shape lives in
 * providers/types.ts.
 */
export function chatChunkToWire(
  chunk: { type: string } & Record<string, unknown>,
): BridgeChatChunk {
  switch (chunk.type) {
    case "text":
      return { kind: "text", delta: chunk.delta as string };
    case "tool_call":
      return {
        kind: "tool_call",
        id: chunk.id as string,
        name: chunk.name as string,
        argsJson: chunk.argsJson as string,
      };
    case "tool_result":
      return {
        kind: "tool_result",
        id: chunk.id as string,
        resultJson: chunk.resultJson as string,
      };
    case "error":
      return {
        kind: "error",
        message: chunk.message as string,
        recoverable: chunk.recoverable as boolean | undefined,
      };
    case "done":
      return {
        kind: "done",
        reason: chunk.reason as BridgeChatChunk extends { kind: "done" }
          ? Extract<BridgeChatChunk, { kind: "done" }>["reason"]
          : never,
      };
    default:
      return { kind: "error", message: `unknown chunk type: ${chunk.type}` };
  }
}

export function extractToolText(result: unknown): string {
  if (typeof result === "string") return result;

  const candidate = result as ToolResultLike | undefined;
  if (candidate?.content && Array.isArray(candidate.content)) {
    return candidate.content
      .filter((part): part is ToolTextPart => part?.type === "text")
      .map((part) => part.text)
      .join("\n");
  }

  try {
    return JSON.stringify(result, null, 2);
  } catch {
    return String(result);
  }
}

export function extractToolImages(
  result: unknown,
): Array<{ data: string; mimeType: string }> {
  const candidate = result as ToolResultLike | undefined;
  if (!candidate?.content || !Array.isArray(candidate.content)) return [];

  return candidate.content
    .filter((part): part is ToolImagePart => part?.type === "image")
    .map((part) => ({ data: part.data, mimeType: part.mimeType }));
}

export function extractToolError(result: unknown): string | undefined {
  const text = extractToolText(result).trim();
  if (!text) return undefined;

  try {
    const parsed = JSON.parse(text);
    if (
      parsed &&
      typeof parsed === "object" &&
      (("error" in parsed && typeof parsed.error === "string") ||
        parsed.success === false)
    ) {
      return typeof parsed.error === "string"
        ? parsed.error
        : "Tool execution failed";
    }
  } catch {
    // Plain text result.
  }

  return undefined;
}

export function getDefaultRawExecutionTool(
  app: string,
): "eval_officejs" | "execute_office_js" | undefined {
  const normalized = app.toLowerCase();
  if (normalized === "excel") return "eval_officejs";
  if (normalized === "powerpoint" || normalized === "word") {
    return "execute_office_js";
  }
  return undefined;
}
